{% set name = "peakqc" %}
{% set version = "0.1.3" %}
{% set sha256 = "c7aa2c5d99058c92514f75b016ac51f27472844e7ddb3307666e17729b7f252c" %}

package:
  name: peakqc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/peakqc/peakqc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports :
    - {{ pin_subpackage({{ peakqc }} , max_pin="x.x") }}

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - matplotlib-base
    - tqdm
    - beartype
    - scanpy >=1.9
    - pysam
    - scipy

test:
  imports:
    - peakqc
  commands:
    - pip check
    - python -c "import peakqc; print(peakqc.__version__)"
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/peakqc/
  summary: Module for quality control of ATAC-seq data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan1034
